parameters:
#    egoe_calcul.example.class: Egoe\CalculBundle\Example

services:
#    egoe_calcul.example:
#        class: %egoe_calcul.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    egoe_calcul.calculator:
        class: Egoe\CalculBundle\Calculator\Calculator